#!/bin/bash

kubectl run -i --restart=Never health-check --rm --image=minio/mc --command -- sh -c '
set -ex
mc config host add test-minio http://minio-service:9000 minio minio123
mc mb test
INPUT="Hello from object storage"
echo -n "$INPUT" | mc pipe minio-test/test/object001
OUTPUT="$(mc cat minio-test/test/object001)"
[[ "$OUTPUT" = "$INPUT" ]] || exit 1'
