# Based on upstream https://raw.githubusercontent.com/minio/minio-operator/12fc1fc1e0179f6178c456b6a3d9430f4f88ea90/examples/minioinstance.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
stringData:
  accesskey: minio
  secretkey: minio123
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio
---
apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio
spec:
  metadata:
    labels:
      app: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  image: minio/minio:RELEASE.2020-06-18T02-23-35Z
  serviceName: minio-internal
  zones:
  - name: "zone-0"
    servers: 1
  volumesPerServer: 1
  mountPath: /export
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
  credsSecret:
    name: minio-credentials
  podManagementPolicy: Parallel
  requestAutoCert: false
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1
