name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.4.0
      with:
        version: v0.8.1
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: 3.8.0
    - name: Apply operator
      run: kustomize build github.com/minio/minio-operator/operator-deployment?ref=2.0.8 | kubectl apply -f -
    - name: Apply overlay
      run: kustomize build envs/kind | kubectl apply -f -
    - name: Wait for operator to be Ready
      run: kubectl wait deployment -n minio-operator minio-operator --for=condition=Available
    - name: Wait for minio to be Ready
      run: |
        until [[ "$(kubectl get minioinstance minio '--output=go-template={{.status.currentState}}')" = "Ready" ]]
        do
          sleep 1
        done
        until [[ "$(kubectl get statefulset minio '--output=go-template={{.status.readyReplicas}}')" = "1" ]]
        do
          sleep 1
        done
    - name: Check if service is working as expected
      run: |
        kubectl run -i --restart=Never health-check --rm --image=minio/mc --command -- sh -c '
        set -ex
        mc config host add test-minio http://minio-service:9000 minio minio123
        mc mb test
        INPUT="Hello from object storage"
        echo -n "$INPUT" | mc pipe minio-test/test/object001
        OUTPUT="$(mc cat minio-test/test/object001)"
        [[ "$OUTPUT" = "$INPUT" ]] || exit 1'
